version: "3.0"
services:
  fields-selector:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "fields-selector"
      MODULE_TYPE: "Processing"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
      ACTION: "keep"
      FIELDS: "temperature, volume, rpm"
    ports:
      - 80:80
